version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
        - ./MessageBroker/rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
        - ./MessageBroker/rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        - ./MessageBroker/rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
        - ./MessageBroker/rabbitmq/logs:/var/log/rabbitmq/log
    ports:
        - 5672:5672
        - 15672:15672

  videocapture:
        container_name: "videocapture"
        build: ./VideoCapture
        restart: always
        command: ["python3","server.py"]
        depends_on:
            - rabbitmq
        volumes:
            - /efs/data/:/efs/data
        ports:
            - "4000:4000"

  playerpucktracking:
    container_name: "playerpucktracking"
    build: ./Ppt
    restart: always
    command: ["python","emit_log2.py"]
    depends_on: 
        -  rabbitmq
    ports:
        - "6000:6000"

  openvino:
        container_name: "openvino"
        build: ./Openvino
        volumes:
            - ./Openvino/data/intel/person-detection-retail-0013/FP32/person-detection-retail-0013.xml:/code/Openvino/data/intel/person-detection-retail-0013/FP32/person-detection-retail-0013.xml
            - ./Openvino/data/intel/person-detection-retail-0013/FP32/person-detection-retail-0013.bin:/code/Openvino/data/intel/person-detection-retail-0013/FP32/person-detection-retail-0013.bin
        restart: always
        user: root
        command: ["python3","openvino_server.py"]
        environment: 
            LD_LIBRARY_PATH: /opt/intel/openvino/data_processing/dl_streamer/lib:/opt/intel/openvino/data_processing/gstreamer/lib:/opt/intel/openvino/opencv/lib:/opt/intel/openvino/deployment_tools/ngraph/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino/deployment_tools/inference_engine/lib/intel64:/opt/intel/openvino/data_processing/dl_streamer/lib:/opt/intel/openvino/data_processing/gstreamer/lib:/opt/intel/openvino/opencv/lib:/opt/intel/openvino/deployment_tools/ngraph/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino/deployment_tools/inference_engine/lib/intel64:LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36
            GST_PLUGIN_PAT: /opt/intel/openvino/data_processing/dl_streamer/lib:/opt/intel/openvino/data_processing/gstreamer/lib/gstreamer-1.0
            INTEL_CVSDK_DIR: /opt/intel/openvino
            GST_VAAPI_ALL_DRIVERS: 1
            MODELS_PATH: /root/intel/dl_streamer/models
            OpenCV_DIR: /opt/intel/openvino/opencv/cmake
            PWD: /usr/lib/python3.6
            InferenceEngine_DIR: /opt/intel/openvino/deployment_tools/inference_engine/share
            HOME: /root
            GI_TYPELIB_PATH: /opt/intel/openvino/data_processing/gstreamer/lib/girepository-1.0
            LIBRARY_PATH: /opt/intel/openvino/data_processing/dl_streamer/lib:/opt/intel/openvino/data_processing/gstreamer/lib:/opt/intel/openvino/data_processing/dl_streamer/lib:/opt/intel/openvino/data_processing/gstreamer/lib
            LC_NUMERIC: C
            ngraph_DIR: /opt/intel/openvino/deployment_tools/ngraph/cmake
            TERM: xterm
            GST_SAMPLES_DIR: /opt/intel/openvino/data_processing/dl_streamer/samples
            SHLVL: 1
            PYTHONPATH: /opt/intel/openvino/python/python3.6:/opt/intel/openvino/python/python3:/opt/intel/openvino/deployment_tools/model_optimizer:/opt/intel/openvino/data_processing/dl_streamer/python:/opt/intel/openvino/data_processing/gstreamer/lib/python3.6/site-packages:/opt/intel/openvino/python/python3.6:/opt/intel/openvino/python/python3:/opt/intel/openvino/deployment_tools/model_optimizer:/opt/intel/openvino/data_processing/dl_streamer/python:/opt/intel/openvino/data_processing/gstreamer/lib/python3.6/site-packages
            GST_PLUGIN_SCANNER: /opt/intel/openvino/data_processing/gstreamer/bin/gstreamer-1.0/gst-plugin-scanner
            INTEL_OPENVINO_DIR: /opt/intel/openvino
            PATH: /opt/intel/openvino/deployment_tools/model_optimizer:/opt/intel/openvino/data_processing/gstreamer/bin:/opt/intel/openvino/data_processing/gstreamer/bin/gstreamer-1.0:/opt/intel/openvino/deployment_tools/model_optimizer:/opt/intel/openvino/data_processing/gstreamer/bin:/opt/intel/openvino/data_processing/gstreamer/bin/gstreamer-1.0:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            PKG_CONFIG_PATH: /opt/intel/openvino/data_processing/dl_streamer/lib/pkgconfig:/opt/intel/openvino/data_processing/gstreamer/lib/pkgconfig:/opt/intel/openvino/data_processing/dl_streamer/lib/pkgconfig:/opt/intel/openvino/data_processing/gstreamer/lib/pkgconfig
            PYTHON: python3.6        
            HDDL_INSTALL_DIR: /opt/intel/openvino/deployment_tools/inference_engine/external/hddl
            _: /usr/bin/env
            OLDPWD: /code
        depends_on:
            - rabbitmq
            - videocapture
        ports:
            - "5000:5000"

        
